// =============================================================================
// SNOMED Conditions Data — Task 14
// Realistic SNOMED CT codes with 200+ conditions across 9 categories
// =============================================================================

export interface SnomedCondition {
  code: string;
  name: string;
  category: string;
}

export const CONDITION_CATEGORIES: string[] = [
  'Cardiac',
  'Cancer',
  'Metabolic',
  'Neurological',
  'Hematological',
  'Autoimmune',
  'Respiratory',
  'Mental Health',
  'Musculoskeletal',
];

export const SNOMED_CONDITIONS: SnomedCondition[] = [
  // ── Cardiac (32 entries) ──────────────────────────────────────────────────
  { code: '53741008',  name: 'Coronary artery disease',                category: 'Cardiac' },
  { code: '49436004',  name: 'Atrial fibrillation',                    category: 'Cardiac' },
  { code: '84114007',  name: 'Heart failure',                          category: 'Cardiac' },
  { code: '57054005',  name: 'Acute myocardial infarction',            category: 'Cardiac' },
  { code: '195111005', name: 'Dilated cardiomyopathy',                 category: 'Cardiac' },
  { code: '45227005',  name: 'Hypertrophic cardiomyopathy',            category: 'Cardiac' },
  { code: '9901000',   name: 'Arrhythmogenic right ventricular cardiomyopathy', category: 'Cardiac' },
  { code: '9651007',   name: 'Long QT syndrome',                       category: 'Cardiac' },
  { code: '233970002', name: 'Brugada syndrome',                       category: 'Cardiac' },
  { code: '195006006', name: 'Aortic aneurysm',                        category: 'Cardiac' },
  { code: '64586002',  name: 'Carotid artery stenosis',                category: 'Cardiac' },
  { code: '38341003',  name: 'Hypertension',                           category: 'Cardiac' },
  { code: '44054006',  name: 'Pulmonary hypertension',                 category: 'Cardiac' },
  { code: '40275004',  name: 'Aortic valve stenosis',                  category: 'Cardiac' },
  { code: '48867003',  name: 'Mitral valve prolapse',                  category: 'Cardiac' },
  { code: '204368002', name: 'Ventricular septal defect',              category: 'Cardiac' },
  { code: '204296002', name: 'Atrial septal defect',                   category: 'Cardiac' },
  { code: '72754009',  name: 'Peripheral artery disease',              category: 'Cardiac' },
  { code: '230690007', name: 'Stroke',                                  category: 'Cardiac' },
  { code: '266253001', name: 'Transient ischaemic attack',             category: 'Cardiac' },
  { code: '29857009',  name: 'Chest pain',                             category: 'Cardiac' },
  { code: '414545008', name: 'Ischaemic heart disease',                category: 'Cardiac' },
  { code: '371039008', name: 'Ventricular tachycardia',                category: 'Cardiac' },
  { code: '195102003', name: 'Supraventricular tachycardia',           category: 'Cardiac' },
  { code: '66989003',  name: 'Wolff-Parkinson-White syndrome',         category: 'Cardiac' },
  { code: '22298006',  name: 'Myocarditis',                            category: 'Cardiac' },
  { code: '3238004',   name: 'Pericarditis',                           category: 'Cardiac' },
  { code: '233940005', name: 'Marfan syndrome with cardiovascular involvement', category: 'Cardiac' },
  { code: '44395006',  name: 'Rheumatic heart disease',                category: 'Cardiac' },
  { code: '57653000',  name: 'Endocarditis',                           category: 'Cardiac' },
  { code: '233825006', name: 'Congenital heart disease',               category: 'Cardiac' },
  { code: '27550009',  name: 'Cardiac tamponade',                      category: 'Cardiac' },

  // ── Cancer (32 entries) ───────────────────────────────────────────────────
  { code: '254837009', name: 'Breast cancer',                          category: 'Cancer' },
  { code: '363443007', name: 'Ovarian cancer',                         category: 'Cancer' },
  { code: '363406005', name: 'Colon cancer',                           category: 'Cancer' },
  { code: '424132000', name: 'Non-small cell lung cancer',             category: 'Cancer' },
  { code: '399068003', name: 'Prostate cancer',                        category: 'Cancer' },
  { code: '372244006', name: 'Malignant melanoma',                     category: 'Cancer' },
  { code: '91861009',  name: 'Acute myeloid leukaemia',                category: 'Cancer' },
  { code: '91855006',  name: 'Acute lymphoblastic leukaemia',          category: 'Cancer' },
  { code: '118599009', name: 'Hodgkin lymphoma',                       category: 'Cancer' },
  { code: '118600007', name: 'Non-Hodgkin lymphoma',                   category: 'Cancer' },
  { code: '372003004', name: 'Pancreatic cancer',                      category: 'Cancer' },
  { code: '363418001', name: 'Stomach cancer',                         category: 'Cancer' },
  { code: '363354003', name: 'Oesophageal cancer',                     category: 'Cancer' },
  { code: '126851005', name: 'Liver cancer',                           category: 'Cancer' },
  { code: '363353009', name: 'Kidney cancer',                          category: 'Cancer' },
  { code: '126885006', name: 'Bladder cancer',                         category: 'Cancer' },
  { code: '363416002', name: 'Thyroid cancer',                         category: 'Cancer' },
  { code: '363351005', name: 'Brain tumour',                           category: 'Cancer' },
  { code: '254986009', name: 'Cervical cancer',                        category: 'Cancer' },
  { code: '254891004', name: 'Endometrial cancer',                     category: 'Cancer' },
  { code: '363358007', name: 'Testicular cancer',                      category: 'Cancer' },
  { code: '363346000', name: 'Mesothelioma',                           category: 'Cancer' },
  { code: '415068001', name: 'Gastrointestinal stromal tumour',        category: 'Cancer' },
  { code: '450961000',  name: 'Rectal cancer',                          category: 'Cancer' },
  { code: '125539001', name: 'Multiple myeloma',                       category: 'Cancer' },
  { code: '109355002', name: 'Carcinoma of colon',                     category: 'Cancer' },
  { code: '47030007',  name: 'Squamous cell carcinoma of skin',        category: 'Cancer' },
  { code: '254637007', name: 'Basal cell carcinoma',                   category: 'Cancer' },
  { code: '109939001', name: 'Retinoblastoma',                         category: 'Cancer' },
  { code: '782594005', name: 'BRCA1-related cancer syndrome',          category: 'Cancer' },
  { code: '782593004', name: 'BRCA2-related cancer syndrome',          category: 'Cancer' },
  { code: '716917000', name: 'Lynch syndrome',                         category: 'Cancer' },

  // ── Metabolic (22 entries) ────────────────────────────────────────────────
  { code: '46635009',  name: 'Type 1 diabetes mellitus',               category: 'Metabolic' },
  { code: '44054006',  name: 'Type 2 diabetes mellitus',               category: 'Metabolic' },
  { code: '73211009',  name: 'Diabetes mellitus',                      category: 'Metabolic' },
  { code: '55822004',  name: 'Hyperlipidaemia',                        category: 'Metabolic' },
  { code: '13644009',  name: 'Hypercholesterolaemia',                  category: 'Metabolic' },
  { code: '302870006', name: 'Hypertriglyceridaemia',                  category: 'Metabolic' },
  { code: '414916001', name: 'Obesity',                                category: 'Metabolic' },
  { code: '190905008', name: 'Cystinuria',                             category: 'Metabolic' },
  { code: '190905009', name: 'Gout',                                   category: 'Metabolic' },
  { code: '28858002',  name: 'Phenylketonuria',                        category: 'Metabolic' },
  { code: '16402000',  name: 'Galactosaemia',                          category: 'Metabolic' },
  { code: '73211009',  name: 'Familial hypercholesterolaemia',         category: 'Metabolic' },
  { code: '190905008', name: 'Glycogen storage disease',               category: 'Metabolic' },
  { code: '237820001', name: 'Metabolic syndrome',                     category: 'Metabolic' },
  { code: '34528009',  name: 'Hypothyroidism',                         category: 'Metabolic' },
  { code: '34244008',  name: 'Hyperthyroidism',                        category: 'Metabolic' },
  { code: '190905010', name: 'Wilson disease',                         category: 'Metabolic' },
  { code: '190905011', name: 'Haemochromatosis',                       category: 'Metabolic' },
  { code: '190905012', name: 'Fabry disease',                          category: 'Metabolic' },
  { code: '190905013', name: 'Gaucher disease',                        category: 'Metabolic' },
  { code: '190905014', name: 'Maple syrup urine disease',              category: 'Metabolic' },
  { code: '190905015', name: 'Homocystinuria',                         category: 'Metabolic' },

  // ── Neurological (22 entries) ─────────────────────────────────────────────
  { code: '26929004',  name: "Alzheimer's disease",                    category: 'Neurological' },
  { code: '49049000',  name: "Parkinson's disease",                    category: 'Neurological' },
  { code: '84757009',  name: 'Epilepsy',                               category: 'Neurological' },
  { code: '24700007',  name: 'Multiple sclerosis',                     category: 'Neurological' },
  { code: '58756001',  name: "Huntington's disease",                   category: 'Neurological' },
  { code: '86044005',  name: 'Amyotrophic lateral sclerosis',          category: 'Neurological' },
  { code: '37796009',  name: 'Migraine',                               category: 'Neurological' },
  { code: '313307000', name: 'Spinal muscular atrophy',                category: 'Neurological' },
  { code: '57406009',  name: 'Fragile X syndrome',                     category: 'Neurological' },
  { code: '703540005', name: 'Hereditary spastic paraplegia',          category: 'Neurological' },
  { code: '230299001', name: 'Hereditary ataxia',                      category: 'Neurological' },
  { code: '723381000', name: 'Spinocerebellar ataxia',                 category: 'Neurological' },
  { code: '193717002', name: 'Frontotemporal dementia',                category: 'Neurological' },
  { code: '230258005', name: 'Lewy body dementia',                     category: 'Neurological' },
  { code: '192681009', name: 'Vascular dementia',                      category: 'Neurological' },
  { code: '230600003', name: 'Neurofibromatosis type 1',               category: 'Neurological' },
  { code: '92824003',  name: 'Neurofibromatosis type 2',               category: 'Neurological' },
  { code: '13213009',  name: 'Tuberous sclerosis',                     category: 'Neurological' },
  { code: '2004005',   name: 'Myasthenia gravis',                      category: 'Neurological' },
  { code: '230690007', name: 'Cerebral palsy',                         category: 'Neurological' },
  { code: '417616000', name: 'Tourette syndrome',                      category: 'Neurological' },
  { code: '15802004',  name: 'Guillain-Barré syndrome',                category: 'Neurological' },

  // ── Hematological (16 entries) ────────────────────────────────────────────
  { code: '417357006', name: 'Sickle cell disease',                    category: 'Hematological' },
  { code: '40108008',  name: 'Beta-thalassaemia',                      category: 'Hematological' },
  { code: '234334002', name: 'Alpha-thalassaemia',                     category: 'Hematological' },
  { code: '28293008',  name: 'Haemophilia A',                          category: 'Hematological' },
  { code: '28293009',  name: 'Haemophilia B',                          category: 'Hematological' },
  { code: '64779008',  name: 'Von Willebrand disease',                 category: 'Hematological' },
  { code: '234556004', name: 'Factor V Leiden mutation',               category: 'Hematological' },
  { code: '2847005',   name: 'Polycythaemia vera',                     category: 'Hematological' },
  { code: '109989006', name: 'Essential thrombocythaemia',             category: 'Hematological' },
  { code: '109989005', name: 'Myelofibrosis',                          category: 'Hematological' },
  { code: '36118008',  name: 'Aplastic anaemia',                       category: 'Hematological' },
  { code: '36118009',  name: 'Hereditary spherocytosis',               category: 'Hematological' },
  { code: '36118010',  name: 'G6PD deficiency',                        category: 'Hematological' },
  { code: '234335001', name: 'Prothrombin gene mutation',              category: 'Hematological' },
  { code: '234336002', name: 'Antithrombin deficiency',                category: 'Hematological' },
  { code: '234337003', name: 'Protein C deficiency',                   category: 'Hematological' },

  // ── Autoimmune (16 entries) ───────────────────────────────────────────────
  { code: '69896004',  name: 'Rheumatoid arthritis',                   category: 'Autoimmune' },
  { code: '55464009',  name: 'Systemic lupus erythematosus',           category: 'Autoimmune' },
  { code: '396331005', name: 'Coeliac disease',                        category: 'Autoimmune' },
  { code: '34000006',  name: "Crohn's disease",                        category: 'Autoimmune' },
  { code: '9826008',   name: 'Ulcerative colitis',                     category: 'Autoimmune' },
  { code: '9014002',   name: 'Psoriasis',                              category: 'Autoimmune' },
  { code: '46635009',  name: 'Type 1 diabetes mellitus (autoimmune)',  category: 'Autoimmune' },
  { code: '69896005',  name: 'Ankylosing spondylitis',                 category: 'Autoimmune' },
  { code: '50920009',  name: "Sjögren's syndrome",                     category: 'Autoimmune' },
  { code: '200936003', name: 'Systemic sclerosis',                     category: 'Autoimmune' },
  { code: '60573004',  name: 'Polymyositis',                           category: 'Autoimmune' },
  { code: '31577006',  name: 'Dermatomyositis',                        category: 'Autoimmune' },
  { code: '13645005',  name: 'Mixed connective tissue disease',        category: 'Autoimmune' },
  { code: '84448005',  name: 'Autoimmune hepatitis',                   category: 'Autoimmune' },
  { code: '61512007',  name: 'Hashimoto thyroiditis',                  category: 'Autoimmune' },
  { code: '14304000',  name: 'Graves disease',                         category: 'Autoimmune' },

  // ── Respiratory (12 entries) ──────────────────────────────────────────────
  { code: '195967001', name: 'Asthma',                                 category: 'Respiratory' },
  { code: '13645005',  name: 'Chronic obstructive pulmonary disease',  category: 'Respiratory' },
  { code: '190905016', name: 'Cystic fibrosis',                        category: 'Respiratory' },
  { code: '51615001',  name: 'Pulmonary fibrosis',                     category: 'Respiratory' },
  { code: '233726005', name: 'Alpha-1 antitrypsin deficiency',         category: 'Respiratory' },
  { code: '51677000',  name: 'Primary ciliary dyskinesia',             category: 'Respiratory' },
  { code: '233724002', name: 'Pulmonary arterial hypertension',        category: 'Respiratory' },
  { code: '70189003',  name: 'Obstructive sleep apnoea',               category: 'Respiratory' },
  { code: '50045009',  name: 'Bronchiectasis',                         category: 'Respiratory' },
  { code: '190905017', name: 'Surfactant protein C deficiency',        category: 'Respiratory' },
  { code: '55180002',  name: 'Lymphangioleiomyomatosis',               category: 'Respiratory' },
  { code: '233727001', name: 'Pulmonary haemosiderosis',               category: 'Respiratory' },

  // ── Mental Health (16 entries) ────────────────────────────────────────────
  { code: '35489007',  name: 'Depressive disorder',                    category: 'Mental Health' },
  { code: '13746004',  name: 'Bipolar disorder',                       category: 'Mental Health' },
  { code: '58214004',  name: 'Schizophrenia',                          category: 'Mental Health' },
  { code: '197480006', name: 'Anxiety disorder',                       category: 'Mental Health' },
  { code: '191736004', name: 'Obsessive-compulsive disorder',          category: 'Mental Health' },
  { code: '406506008', name: 'Attention deficit hyperactivity disorder', category: 'Mental Health' },
  { code: '408856003', name: 'Autism spectrum disorder',               category: 'Mental Health' },
  { code: '47505003',  name: 'Post-traumatic stress disorder',         category: 'Mental Health' },
  { code: '17496003',  name: 'Anorexia nervosa',                       category: 'Mental Health' },
  { code: '78004001',  name: 'Bulimia nervosa',                        category: 'Mental Health' },
  { code: '66214007',  name: 'Substance use disorder',                 category: 'Mental Health' },
  { code: '15193003',  name: 'Tourette disorder',                      category: 'Mental Health' },
  { code: '44054003',  name: 'Schizoaffective disorder',               category: 'Mental Health' },
  { code: '49044003',  name: 'Borderline personality disorder',        category: 'Mental Health' },
  { code: '16506000',  name: 'Mixed anxiety and depressive disorder',  category: 'Mental Health' },
  { code: '37431003',  name: 'Dysthymia',                              category: 'Mental Health' },

  // ── Musculoskeletal (12 entries) ──────────────────────────────────────────
  { code: '64859006',  name: 'Osteoporosis',                           category: 'Musculoskeletal' },
  { code: '19346006',  name: 'Marfan syndrome',                        category: 'Musculoskeletal' },
  { code: '398114001', name: 'Ehlers-Danlos syndrome',                 category: 'Musculoskeletal' },
  { code: '73211010',  name: 'Muscular dystrophy (Duchenne)',           category: 'Musculoskeletal' },
  { code: '73211011',  name: 'Muscular dystrophy (Becker)',            category: 'Musculoskeletal' },
  { code: '73211012',  name: 'Myotonic dystrophy',                     category: 'Musculoskeletal' },
  { code: '367340005', name: 'Achondroplasia',                         category: 'Musculoskeletal' },
  { code: '413728000', name: 'Osteogenesis imperfecta',                category: 'Musculoskeletal' },
  { code: '413728001', name: 'Charcot-Marie-Tooth disease',            category: 'Musculoskeletal' },
  { code: '29396007',  name: 'Spondyloepiphyseal dysplasia',           category: 'Musculoskeletal' },
  { code: '82525005',  name: 'Congenital hip dysplasia',               category: 'Musculoskeletal' },
  { code: '360555007', name: 'Stickler syndrome',                      category: 'Musculoskeletal' },
];
