/**
 * chart-export.util.ts
 *
 * Pure export utility functions for the family pedigree chart.
 * No Angular dependencies — these can be called from any context.
 */

import { FamilyMember, FamilyCondition } from '../data-access/family.models';

// =============================================================================
// SVG export
// =============================================================================

/**
 * Serializes the given SVGElement to a Blob and triggers a browser download.
 */
export function exportSVG(svgElement: SVGElement, filename: string): void {
  const serializer = new XMLSerializer();
  const svgStr = serializer.serializeToString(svgElement);
  const blob = new Blob(
    [`<?xml version="1.0" encoding="utf-8"?>\n${svgStr}`],
    { type: 'image/svg+xml;charset=utf-8' }
  );
  triggerDownload(blob, ensureExtension(filename, '.svg'));
}

// =============================================================================
// PNG export
// =============================================================================

/**
 * Renders the SVG to a canvas and exports as PNG.
 * Uses the browser's Image and Canvas APIs — no external dependency required.
 */
export function exportPNG(svgElement: SVGElement, filename: string): void {
  const serializer = new XMLSerializer();
  const svgStr = serializer.serializeToString(svgElement);
  const svgBlob = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8' });
  const url = URL.createObjectURL(svgBlob);

  const img = new Image();
  img.onload = () => {
    const canvas = document.createElement('canvas');
    const scale  = window.devicePixelRatio || 2;
    canvas.width  = img.width  * scale;
    canvas.height = img.height * scale;

    const ctx = canvas.getContext('2d');
    if (!ctx) {
      URL.revokeObjectURL(url);
      return;
    }

    ctx.scale(scale, scale);
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(img, 0, 0);
    URL.revokeObjectURL(url);

    canvas.toBlob(blob => {
      if (blob) triggerDownload(blob, ensureExtension(filename, '.png'));
    }, 'image/png');
  };

  img.onerror = () => URL.revokeObjectURL(url);
  img.src = url;
}

// =============================================================================
// Printable HTML export
// =============================================================================

/**
 * Opens a new browser window with a print-ready HTML pedigree summary.
 */
export function exportPrintableHTML(
  members: FamilyMember[],
  conditions: FamilyCondition[]
): void {
  const now = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const memberRows = members
    .filter(m => !m.isPet)
    .map(m => {
      const memberConditions = conditions
        .filter(c => c.memberId === m.id)
        .map(c => `${c.conditionName} (${c.status})`)
        .join('; ') || '—';

      const dob = m.dateOfBirth
        ? m.dateOfBirth.toLocaleDateString('en-US')
        : '—';

      return `
        <tr>
          <td>${m.firstName} ${m.lastName}</td>
          <td>${m.relationship}</td>
          <td>${m.sexAtBirth}</td>
          <td>${dob}</td>
          <td>${m.isDeceased ? `Deceased (age ${m.deceasedAge ?? '?'})` : 'Living'}</td>
          <td>${memberConditions}</td>
        </tr>
      `;
    })
    .join('');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Family Pedigree Report</title>
  <style>
    body {
      font-family: 'Times New Roman', serif;
      margin: 40px;
      color: #111;
    }
    h1 { font-size: 20px; margin-bottom: 4px; }
    .subtitle { font-size: 12px; color: #555; margin-bottom: 24px; }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 12px;
    }
    th {
      background: #1f2937;
      color: #fff;
      padding: 8px 10px;
      text-align: left;
    }
    td {
      border: 1px solid #d1d5db;
      padding: 6px 10px;
    }
    tr:nth-child(even) td { background: #f9fafb; }
    .footer {
      margin-top: 32px;
      font-size: 10px;
      color: #6b7280;
      border-top: 1px solid #e5e7eb;
      padding-top: 12px;
    }
    @media print {
      body { margin: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <h1>Family Pedigree Report</h1>
  <div class="subtitle">Generated on ${now} — HIPAA-compliant clinical summary</div>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Relationship</th>
        <th>Sex at Birth</th>
        <th>Date of Birth</th>
        <th>Status</th>
        <th>Conditions</th>
      </tr>
    </thead>
    <tbody>
      ${memberRows}
    </tbody>
  </table>

  <div class="footer">
    This report was generated by the GoHealth Patient Portal Family History module.
    For clinical use only. Handle in accordance with HIPAA regulations.
  </div>

  <script>
    window.onload = function() { window.print(); };
  </script>
</body>
</html>`;

  const win = window.open('', '_blank');
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}

// =============================================================================
// CanRisk format export
// =============================================================================

/**
 * Generates a CanRisk-compatible pedigree text format.
 * CanRisk is used by the Manchester CanRisk tool for BRCA/BOADICEA risk modelling.
 *
 * Returns the formatted string — caller decides how to present/download it.
 *
 * Reference: https://canrisk.org/canrisk_file_format/
 */
export function exportCanRisk(members: FamilyMember[]): string {
  const lines: string[] = [];

  lines.push('##CanRisk 2.0');
  lines.push('##HEADER');
  lines.push('##FamID\tName\tTarget\tIndivID\tFathID\tMothID\tSex\tMZtwin\tDead\tAge\tYob\tBC1\tBC2\tOC\tPRO\tPAN\tAshkn\tBRCA1\tBRCA2\tPALB2\tATM\tCHEK2\tBARD1\tRAD51D\tRAD51C\tBRIP1\tER:PR:HER2:CK14:CK56');
  lines.push('##DATA');

  const proband = members.find(m => m.isProband);
  const probandId = proband?.id ?? 'fm-001';

  // Map member IDs to simple integer IDs for CanRisk
  const idMap = new Map<string, number>();
  members.forEach((m, i) => idMap.set(m.id, i + 1));

  for (const member of members) {
    if (member.isPet) continue;

    const famId   = '1';
    const name    = `${member.firstName.replace(/\s/g, '_')}_${member.lastName.replace(/\s/g, '_')}`;
    const target  = member.isProband ? '1' : '0';
    const indivId = String(idMap.get(member.id) ?? 0);
    const fathId  = '0'; // Simplified — full pedigree linkage requires parent IDs
    const mothId  = '0';
    const sex     = member.sexAtBirth === 'male' ? 'M' : (member.sexAtBirth === 'female' ? 'F' : 'U');
    const mzTwin  = '0';
    const dead    = member.isDeceased ? '1' : '0';

    const currentYear = new Date().getFullYear();
    const yob = member.dateOfBirth ? member.dateOfBirth.getFullYear() : 0;
    const age = yob > 0
      ? (member.isDeceased ? (member.deceasedAge ?? currentYear - yob) : currentYear - yob)
      : 0;

    // Cancer flags (0 = unaffected, age at diagnosis = affected)
    const bc1 = getCancerAge(member, 'Breast Cancer', 'affected') ?? '0';
    const bc2 = '0'; // Contralateral BC
    const oc  = getCancerAge(member, 'Ovarian Cancer', 'affected') ?? '0';
    const pro = getCancerAge(member, 'Prostate Cancer', 'affected') ?? '0';
    const pan = getCancerAge(member, 'Pancreatic Cancer', 'affected') ?? '0';

    // Ashkenazi Jewish flag — not tracked, default 0
    const ashkn = '0';

    // Genetic test results (0 = not tested, P = pathogenic, N = negative, S = VUS)
    const brca1  = getGeneResult(member, 'BRCA1');
    const brca2  = getGeneResult(member, 'BRCA2');
    const palb2  = getGeneResult(member, 'PALB2');
    const atm    = getGeneResult(member, 'ATM');
    const chek2  = getGeneResult(member, 'CHEK2');
    const bard1  = getGeneResult(member, 'BARD1');
    const rad51d = getGeneResult(member, 'RAD51D');
    const rad51c = getGeneResult(member, 'RAD51C');
    const brip1  = getGeneResult(member, 'BRIP1');

    // ER:PR:HER2:CK14:CK56 tumour markers — not tracked
    const tumour = '0:0:0:0:0';

    const row = [
      famId, name, target, indivId, fathId, mothId, sex, mzTwin, dead,
      String(age), String(yob),
      String(bc1), String(bc2), String(oc), String(pro), String(pan),
      ashkn,
      brca1, brca2, palb2, atm, chek2, bard1, rad51d, rad51c, brip1,
      tumour,
    ].join('\t');

    lines.push(row);
  }

  return lines.join('\n');
}

// =============================================================================
// PED (PLINK pedigree) format export
// =============================================================================

/**
 * Generates a PED format string compatible with PLINK and similar tools.
 *
 * PED format columns:
 *   Family ID | Individual ID | Father ID | Mother ID | Sex | Phenotype
 *
 * Returns the formatted string.
 */
export function exportPED(members: FamilyMember[]): string {
  const lines: string[] = [];
  lines.push('# PED format generated by GoHealth Patient Portal');
  lines.push('# FamilyID IndividualID FatherID MotherID Sex(1=M,2=F,other=0) Phenotype(1=ctrl,2=case,-9=missing)');

  const famId = '1';
  const idMap = new Map<string, number>();
  members.forEach((m, i) => idMap.set(m.id, i + 1));

  for (const member of members) {
    if (member.isPet) continue;

    const indivId = String(idMap.get(member.id) ?? 0);
    const fathId  = '0';
    const mothId  = '0';
    const sex     = member.sexAtBirth === 'male' ? '1' : (member.sexAtBirth === 'female' ? '2' : '0');

    // Phenotype: 2 = affected (any condition), 1 = unaffected, -9 = unknown
    let phenotype = '1';
    if (member.conditions.some(c => c.status === 'affected')) {
      phenotype = '2';
    } else if (member.conditions.some(c => c.status === 'unknown')) {
      phenotype = '-9';
    }

    lines.push([famId, indivId, fathId, mothId, sex, phenotype].join('\t'));
  }

  return lines.join('\n');
}

// =============================================================================
// Private helpers
// =============================================================================

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a   = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function ensureExtension(filename: string, ext: string): string {
  return filename.endsWith(ext) ? filename : `${filename}${ext}`;
}

function getCancerAge(
  member: FamilyMember,
  conditionName: string,
  status: string
): number | null {
  const condition = member.conditions.find(
    c => c.conditionName.toLowerCase().includes(conditionName.toLowerCase()) &&
         c.status === status
  );
  return condition?.onsetAge ?? null;
}

function getGeneResult(member: FamilyMember, geneName: string): string {
  const test = member.geneticTests.find(
    t => t.geneName.toUpperCase() === geneName.toUpperCase()
  );
  if (!test) return '0';
  switch (test.classification) {
    case 'pathogenic':
    case 'likely-pathogenic': return 'P';
    case 'benign':
    case 'likely-benign':    return 'N';
    case 'vus':               return 'S';
    default:                  return '0';
  }
}
