import { Routes } from '@angular/router';
import { authGuard, mfaGuard, guestGuard } from './shared/utils';

export const routes: Routes = [
  { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
  { path: 'onboarding', loadComponent: () => import('./onboarding/feature/onboarding.component').then(m => m.OnboardingComponent) },
  { path: 'login', canActivate: [guestGuard], loadComponent: () => import('./auth/feature/login.component').then(m => m.LoginComponent) },
  { path: 'forgot-password', canActivate: [guestGuard], loadComponent: () => import('./auth/feature/forgot-password.component').then(m => m.ForgotPasswordComponent) },
  { path: 'reset-password', canActivate: [guestGuard], loadComponent: () => import('./auth/feature/reset-password.component').then(m => m.ResetPasswordComponent) },
  { path: 'mfa', loadComponent: () => import('./auth/feature/mfa.component').then(m => m.MfaComponent) },
  {
    path: '',
    canActivate: [authGuard, mfaGuard],
    loadComponent: () => import('./shell/feature/shell.component').then(m => m.ShellComponent),
    children: [
      { path: 'dashboard', loadComponent: () => import('./dashboard/feature/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'appointments', loadComponent: () => import('./appointments/feature/appointments.component').then(m => m.AppointmentsComponent) },
      { path: 'records', loadComponent: () => import('./health-records/feature/health-records.component').then(m => m.HealthRecordsComponent) },
      { path: 'messages', loadComponent: () => import('./messages/feature/messages.component').then(m => m.MessagesComponent) },
      { path: 'messages/:id', loadComponent: () => import('./messages/feature/messages.component').then(m => m.MessagesComponent) },
      { path: 'billing', loadComponent: () => import('./billing/feature/billing.component').then(m => m.BillingComponent) },
      { path: 'forms', loadComponent: () => import('./forms/feature/forms.component').then(m => m.FormsComponent) },
      { path: 'notifications', loadComponent: () => import('./notifications/feature/notifications.component').then(m => m.NotificationsComponent) },
      { path: 'emergency-contacts', loadComponent: () => import('./settings/feature/emergency-contacts.component').then(m => m.EmergencyContactsComponent) },
      { path: 'consent-management', loadComponent: () => import('./settings/feature/consent-management.component').then(m => m.ConsentManagementComponent) },
      { path: 'data-management', loadComponent: () => import('./settings/feature/data-management.component').then(m => m.DataManagementComponent) },
      { path: 'privacy-policy', loadComponent: () => import('./settings/feature/privacy-policy.component').then(m => m.PrivacyPolicyComponent) },
      { path: 'settings', loadComponent: () => import('./settings/feature/settings.component').then(m => m.SettingsComponent) },
      { path: 'telehealth/:appointmentId', loadComponent: () => import('./telehealth/feature/telehealth.component').then(m => m.TelehealthComponent) },
      { path: 'telehealth', loadComponent: () => import('./telehealth/feature/telehealth.component').then(m => m.TelehealthComponent) },
      { path: 'symptom-checker', loadComponent: () => import('./symptom-checker/feature/symptom-checker.component').then(m => m.SymptomCheckerComponent) },
      { path: 'health-timeline', loadComponent: () => import('./health-timeline/feature/health-timeline.component').then(m => m.HealthTimelineComponent) },
      { path: 'lab-trends', loadComponent: () => import('./lab-trends/feature/lab-trends.component').then(m => m.LabTrendsComponent) },
      { path: 'prescriptions', loadComponent: () => import('./prescriptions/feature/prescriptions.component').then(m => m.PrescriptionsComponent) },
      { path: 'devices', loadComponent: () => import('./devices/feature/devices.component').then(m => m.DevicesComponent) },
      { path: 'insurance', loadComponent: () => import('./insurance/feature/insurance.component').then(m => m.InsuranceComponent) },
      { path: 'providers', loadComponent: () => import('./providers/feature/providers.component').then(m => m.ProvidersComponent) },
      { path: 'care-team', loadComponent: () => import('./care-team/feature/care-team.component').then(m => m.CareTeamComponent) },
      { path: 'health-analytics', loadComponent: () => import('./health-analytics/feature/health-analytics.component').then(m => m.HealthAnalyticsComponent) },
      { path: 'questionnaires', loadComponent: () => import('./health-analytics/feature/pro-questionnaires.component').then(m => m.ProQuestionnairesComponent) },
      { path: 'triage', loadComponent: () => import('./triage/feature/triage.component').then(m => m.TriageComponent) },
      { path: 'referrals', loadComponent: () => import('./admin-tools/feature/referral-tracker.component').then(m => m.ReferralTrackerComponent) },
      { path: 'sick-note', loadComponent: () => import('./admin-tools/feature/sick-note-request.component').then(m => m.SickNoteRequestComponent) },
      { path: 'survey', loadComponent: () => import('./admin-tools/feature/survey.component').then(m => m.SurveyComponent) },
      { path: 'feedback', loadComponent: () => import('./admin-tools/feature/feedback.component').then(m => m.FeedbackComponent) },
      { path: 'record-sharing', loadComponent: () => import('./admin-tools/feature/record-sharing.component').then(m => m.RecordSharingComponent) },
      { path: 'preauth-request', loadComponent: () => import('./admin-tools/feature/preauth-request.component').then(m => m.PreauthRequestComponent) },
      { path: 'abha', loadComponent: () => import('./country/feature/abha-health-id.component').then(m => m.AbhaHealthIdComponent) },
      { path: 'jan-aushadhi', loadComponent: () => import('./country/feature/jan-aushadhi-locator.component').then(m => m.JanAushadhiLocatorComponent) },
      { path: 'des', loadComponent: () => import('./country/feature/des-viewer.component').then(m => m.DesViewerComponent) },
      { path: 'digital-queue', loadComponent: () => import('./country/feature/digital-queue.component').then(m => m.DigitalQueueComponent) },
      { path: 'my-health-record', loadComponent: () => import('./country/feature/my-health-record.component').then(m => m.MyHealthRecordComponent) },
      { path: 'bulk-billing', loadComponent: () => import('./country/feature/bulk-billing-locator.component').then(m => m.BulkBillingLocatorComponent) },
      { path: 'open-notes', loadComponent: () => import('./country/feature/open-notes.component').then(m => m.OpenNotesComponent) },
      { path: 'abdm-locker', loadComponent: () => import('./country/feature/abdm-health-locker.component').then(m => m.AbdmHealthLockerComponent) },
      { path: 'esanjeevani', loadComponent: () => import('./country/feature/esanjeevani.component').then(m => m.EsanjeevaniComponent) },
      { path: 'cowin', loadComponent: () => import('./country/feature/cowin-certificate.component').then(m => m.CowinCertificateComponent) },
      { path: 'cnas', loadComponent: () => import('./country/feature/cnas-prescriptions.component').then(m => m.CnasPrescriptionsComponent) },
      { path: 'ehds', loadComponent: () => import('./country/feature/ehds-roadmap.component').then(m => m.EhdsRoadmapComponent) },
      { path: 'medicare-benefits', loadComponent: () => import('./country/feature/medicare-benefits.component').then(m => m.MedicareBenefitsComponent) },
      { path: 'pbs', loadComponent: () => import('./country/feature/pbs-prescriptions.component').then(m => m.PbsPrescriptionsComponent) },
      { path: 'first-nations', loadComponent: () => import('./country/feature/first-nations-health.component').then(m => m.FirstNationsHealthComponent) },
      { path: 'tis', loadComponent: () => import('./country/feature/tis-interpreter.component').then(m => m.TisInterpreterComponent) },
      { path: 'blue-button', loadComponent: () => import('./country/feature/blue-button.component').then(m => m.BlueButtonComponent) },
      { path: 'cures-act', loadComponent: () => import('./country/feature/cures-act.component').then(m => m.CuresActComponent) },
      { path: 'smart-fhir', loadComponent: () => import('./country/feature/smart-on-fhir.component').then(m => m.SmartOnFhirComponent) },
      { path: 'commonwell', loadComponent: () => import('./country/feature/commonwell.component').then(m => m.CommonwellComponent) },
      { path: 'audit-log', loadComponent: () => import('./settings/feature/audit-log.component').then(m => m.AuditLogComponent) },
      // Visit Summaries, Care Plans, Waitlist
      { path: 'visit-summaries', loadComponent: () => import('./visit-summaries/feature/visit-summaries.component').then(m => m.VisitSummariesComponent) },
      { path: 'care-plans', loadComponent: () => import('./care-plans/feature/care-plans.component').then(m => m.CarePlansComponent) },
      { path: 'waitlist', loadComponent: () => import('./waitlist/feature/waitlist.component').then(m => m.WaitlistComponent) },
      // Family Management routes
      { path: 'family', loadComponent: () => import('./family/feature/family-dashboard.component').then(m => m.FamilyDashboardComponent) },
      { path: 'family/permissions', loadComponent: () => import('./family/feature/permission-management.component').then(m => m.PermissionManagementComponent) },
      { path: 'family/pets/:id', loadComponent: () => import('./family/feature/pet-profile.component').then(m => m.PetProfileComponent) },
      { path: 'family/chart', loadComponent: () => import('./family/feature/family-chart.component').then(m => m.FamilyChartComponent) },
      // Genetic & Family History routes
      { path: 'health/family-history', loadComponent: () => import('./family/feature/family-history.component').then(m => m.FamilyHistoryComponent) },
      { path: 'health/genetic-tests', loadComponent: () => import('./family/feature/genetic-tests.component').then(m => m.GeneticTestsComponent) },
      { path: 'health/genetic-risk', loadComponent: () => import('./family/feature/genetic-risk.component').then(m => m.GeneticRiskComponent) },
      // Medicolegal & Ruleset routes
      { path: 'settings/jurisdiction', loadComponent: () => import('./family/feature/jurisdiction-settings.component').then(m => m.JurisdictionSettingsComponent) },
      { path: 'medications/schedule-reference', loadComponent: () => import('./family/feature/medication-schedule.component').then(m => m.MedicationScheduleComponent) },
      { path: 'telehealth/jurisdiction-check', loadComponent: () => import('./family/feature/telehealth-checker.component').then(m => m.TelehealthCheckerComponent) },
      { path: 'admin/consent-rules', loadComponent: () => import('./family/feature/consent-age-matrix.component').then(m => m.ConsentAgeMatrixComponent) },
      { path: 'admin/proxy-accounts', loadComponent: () => import('./family/feature/proxy-management.component').then(m => m.ProxyManagementComponent) },
      // Check-In & Queue routes
      { path: 'check-in/:appointmentId', loadComponent: () => import('./check-in/feature/check-in.component').then(m => m.CheckInComponent) },
      { path: 'queue-status', loadComponent: () => import('./queue-status/feature/queue-status.component').then(m => m.QueueStatusComponent) }
    ]
  },
  { path: '**', redirectTo: 'dashboard' }
];
